[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true

[git_branch]
truncation_length = 4
truncation_symbol = ""
